### ISSUE TITLE
opencv cmake changes

### ISSUE THREAD

**Issue by adennie** [xuchong/android-opencv-ffmpeg#2]
Hi, can you clarify the changes needed to the opencv cmake files?

I assume that the change to the root CMakeLists.txt is to change 

`OCV_OPTION(WITH_FFMPEG         "Include FFMPEG support"                      ON   IF (NOT ANDROID AND NOT IOS))`
to
`OCV_OPTION(WITH_FFMPEG         "Include FFMPEG support"                      ON   IF (NOT IOS))
`

But the needed change to OpenCVFindLibsVideo.cmake is not as obvious to me.
Thanks!

**Comment by xuchong** [comment]
@adennie  This is my changes in opencv source  when i build opencv with ffmpeg for android.

Wish it can help you.

The details you can found here:
https://gist.github.com/xuchong/31426c624bffd8802ecf17a830bfef53

You can also download the diff files.
[diff.patch.txt](https://github.com/xuchong/android-opencv-ffmpeg/files/1581878/diff.patch.txt)
