### ISSUE TITLE
Recompile Opencv with ffmepg

### ISSUE THREAD

**Issue by huankonghuanmeng** [xuchong/android-opencv-ffmpeg#3]
how to modify root CMakeLists.txt and the next

**Comment by xuchong** [comment]
See [issues 2](https://github.com/xuchong/android-opencv-ffmpeg/issues/2)

**Comment by huankonghuanmeng** [comment]
thanks

**Comment by codeinmyself** [comment]
Can we just use the official opencv4android instead of that compiled  from source code by myself?
And just a quick question, can you provide us with the results( .so/.a) since the process of compile seems too hard for me as a new to opencv?
