### ISSUE TITLE
你好前辈，我QQ能加你为好友么，我在编译过程中出了一些问题，想请教一下前辈

### ISSUE THREAD

**Issue by 1091390146** [xuchong/android-opencv-ffmpeg#5]
我的Q 1091390146

**Comment by xuchong** [comment]
你好，
不是很经常用QQ。有问题，你可以email给我，或者在GitHub的issue中提问。工作比较忙，我尽量及时回复哈。

在 2018年4月12日，下午2:32，潘 <notifications@github.com<mailto:notifications@github.com>> 写道：


我的Q 1091390146

**Comment by 1091390146** [comment]
嗯嗯，前辈是这样的，我已经把opencv源码还有ffmpeg，全部编译了一遍，然后步骤4有一点不明白，我用的是mk进行编译，不是cmake，我需要修改opencv的mk文件，里面添加ffmpeg的静态库连接？

**Comment by xuchong** [comment]
由于以前的Android library不包含ffmpeg静态库，现在需要将编译好的ffmpeg 静态库添加到编译库中。

在 2018年4月13日，下午5:17，潘 <notifications@github.com<mailto:notifications@github.com>> 写道：


嗯嗯，前辈是这样的，我已经把opencv源码还有ffmpeg，全部编译了一遍，然后步骤4有一点不明白，我用的是mk进行编译，不是cmake，我需要修改opencv的mk文件，里面添加ffmpeg的静态库连接？

**Comment by 1091390146** [comment]
现在您的demo中已经有opencv各种静态库的链接以及java3动态库，您的意思是我在cmake文件里面再添加ffmpeg的静态库么

**Comment by 1091390146** [comment]
我已经按照问题2说明的配置完成了cmake文件，接下来再直接编译改变cmake文件的opencv源码就可以了么？
