### ISSUE TITLE
How can I compile opencv with ffmpeg

### ISSUE THREAD

**Issue by hadjiii** [xuchong/android-opencv-ffmpeg#6]
Hi.
After building ffmpeg for android, I have a new folder named "**android**" in which there are folders refering  architectures  such as **arm, x86**...
My problem is I don't know how **to compile OpenCV with ffmpeg**.

I am working in a project and I need your help.

Best Regards.

**Comment by xuchong** [comment]
Use the compiled ffmpeg outputs(header, libraries) for android. Then do the forth step. https://gist.github.com/xuchong/31426c624bffd8802ecf17a830bfef53

**Comment by hadjiii** [comment]
Thank you.
But I still have the same problem.
Here are my outputs after ffmpeg compilation:
<img width="389" alt="arch" src="https://user-images.githubusercontent.com/36597604/40962683-7e09d400-68a6-11e8-9d31-210c655fd68e.PNG">
I don't know where I have to put them and make a link with OpenCV.

I have already done configurations according to https://gist.github.com/xuchong/31426c624bffd8802ecf17a830bfef53 .

**Comment by xuchong** [comment]
You can refer to the standard OpenCV compiling proccess with ffmpeg.

**Comment by hadjiii** [comment]
Thanks !
